
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author UFPSO
 */
public class Menu extends javax.swing.JFrame {

    Parqueadero usuario [];
    DefaultTableModel modelo;
    int con=0;
    int n=0;
    public Menu() {
        initComponents();
        
        
        modelo=new DefaultTableModel();
        datos.setModel(modelo);
        modelo.addColumn("Nombre");
        modelo.addColumn("Tipo");
        modelo.addColumn("Marca");
        modelo.addColumn("Placa");
        modelo.addColumn("Color");
        modelo.addColumn("Fecha y hora");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Placa = new javax.swing.JLabel();
        placa = new javax.swing.JTextField();
        Marca = new javax.swing.JLabel();
        marca = new javax.swing.JTextField();
        Color = new javax.swing.JLabel();
        color = new javax.swing.JTextField();
        Tipo = new javax.swing.JLabel();
        tipo = new javax.swing.JComboBox<String>();
        Nombre = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        Plazas = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        Consultar = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        numMotosCarros = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        datos = new javax.swing.JTable();
        Hora = new javax.swing.JLabel();
        hora = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PARQUEADERO");

        Placa.setText("N° de placa");

        placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placaActionPerformed(evt);
            }
        });

        Marca.setText("Marca");

        Color.setText("Color");

        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });

        Tipo.setText("Tipo de vehiculo");

        tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Automovil", "Motocicleta" }));

        Nombre.setText("Nombre del propetario");

        Plazas.setText("Plazas del parqueadero");
        Plazas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlazasActionPerformed(evt);
            }
        });

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        Consultar.setText("Consultar");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });

        numMotosCarros.setText("N° de motos y autos");
        numMotosCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numMotosCarrosActionPerformed(evt);
            }
        });

        datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(datos);

        Hora.setText("Hora de ingreso");

        hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Placa)
                                            .addComponent(Marca)
                                            .addComponent(Color)
                                            .addComponent(Tipo))
                                        .addGap(54, 54, 54)
                                        .addComponent(placa, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Nombre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nombre)
                                            .addComponent(tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hora))))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Plazas)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Guardar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Consultar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Modificar)
                                        .addGap(18, 18, 18)
                                        .addComponent(Buscar))
                                    .addComponent(numMotosCarros)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(245, 245, 245)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Hora)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Placa)
                    .addComponent(placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Plazas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Marca)
                    .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Guardar)
                    .addComponent(Consultar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Color)
                    .addComponent(color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Modificar)
                    .addComponent(Buscar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tipo)
                            .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(numMotosCarros)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Hora)
                    .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placaActionPerformed

    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorActionPerformed

    private void PlazasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlazasActionPerformed
        n=Integer.parseInt(JOptionPane.showInputDialog("Diga el numero de plazas"));
        usuario = new Parqueadero[n];
    }//GEN-LAST:event_PlazasActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        if(con<n){
        Parqueadero objparqueadero=new Parqueadero();
        objparqueadero.setNombre(nombre.getText());
        objparqueadero.setTipo(String.valueOf(tipo.getSelectedItem()));
        objparqueadero.setMarca(marca.getText());
        objparqueadero.setPlaca(placa.getText());
        objparqueadero.setColor(color.getText());
       
        usuario[con]=objparqueadero;
        
        con ++;
        }
        else {
            JOptionPane.showMessageDialog(this,"El arreglo esta lleno");
        }
    }//GEN-LAST:event_GuardarActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
         String estados=" ";
        for(int i=0; i<usuario.length;i++){
            
            modelo.insertRow(modelo.getRowCount(),new Object[]{
                usuario[i].getNombre(),
                usuario[i].getTipo(),
                usuario[i].getMarca(),
                usuario[i].getPlaca(),
                usuario[i].getColor(),
                
                estados});
                
            
            
        }
    }//GEN-LAST:event_ConsultarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
       /* String plac=JOptionPane.showInputDialog("Diga la placa del vehiculo");
        for(int i=0; i<usuario.length;i++){
            if(plac==usuario[i].getPlaca()){
                JOptionPane.showMessageDialog(null, usuario[i]+"");
            }
            if(plac!=usuario[i].getPlaca()){
                JOptionPane.showMessageDialog(null,"no se encontro la placa ");
            }
        }*/
        String estados=" ";
        String plac=JOptionPane.showInputDialog("Diga la placa del vehiculo");
        for(int i=0; i<usuario.length;i++){
            
            modelo.insertRow(modelo.getRowCount(),new Object[]{
                usuario[i].getNombre(),
                usuario[i].getTipo(),
                usuario[i].getMarca(),
                usuario[i].getPlaca(),
                usuario[i].getColor(),
                
                estados});
            
            if(plac==usuario[i].getPlaca()){
                JOptionPane.showMessageDialog(null, usuario[i]+"");
            }
            if(plac!=usuario[i].getPlaca()){
                JOptionPane.showMessageDialog(null,"no se encontro la placa ");
            }
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
    /*long docu =Long.valueOf(JOptionPane.showInputDialog(null,"Ingrese el numero de documento a modificar"));
    for(int i=0;i<n;i++){
    if(docu==usuario[i].getPlaca()){
          int edit = Integer.parseInt(JOptionPane.showInputDialog(null,"1. modificar edad \n 2.modificar nombre \n 3. modificar promedio \n 4. modificar costo \n 5. modificar sexo \n 6. modificar estado"));    
            if(edit == 1){ 
            modelo.setValueAt(nombre.getText(), i, 0);
            }
            if(edit == 2){
            modelo.setValueAt(color.getText(), i, 1);
            }
            if(edit == 3){
            modelo.setValueAt(marca.getText(), i, 3);
            }
            if(edit == 4){
            modelo.setValueAt(placa.getText(), i, 5);
            }
            if(edit == 5){
            modelo.setValueAt(tipo.getSelectedItem(), i, 4);
            }
    }
    }*/
    }//GEN-LAST:event_ModificarActionPerformed

    private void numMotosCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numMotosCarrosActionPerformed
        
    }//GEN-LAST:event_numMotosCarrosActionPerformed

    private void horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horaActionPerformed
        String cadena=" ";
        Date date = new Date();
        DateFormat hourdateFormat = new SimpleDateFormat("HH:mm:ss dd/MM/yyyy");
        
    }//GEN-LAST:event_horaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JLabel Color;
    private javax.swing.JButton Consultar;
    private javax.swing.JButton Guardar;
    private javax.swing.JLabel Hora;
    private javax.swing.JLabel Marca;
    private javax.swing.JButton Modificar;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Placa;
    private javax.swing.JButton Plazas;
    private javax.swing.JLabel Tipo;
    private javax.swing.JTextField color;
    private javax.swing.JTable datos;
    private javax.swing.JTextField hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton numMotosCarros;
    private javax.swing.JTextField placa;
    private javax.swing.JComboBox<String> tipo;
    // End of variables declaration//GEN-END:variables
}
